// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQdnH51YN_yFhw-kdaAoTua_WjVreRP8',
    appId: '1:1074728173827:web:004b76b81cf68b38bbe936',
    messagingSenderId: '1074728173827',
    projectId: 'studio-l13dd',
    authDomain: 'studio-l13dd.firebaseapp.com',
    databaseURL: 'https://studio-l13dd-default-rtdb.firebaseio.com',
    storageBucket: 'studio-l13dd.firebasestorage.app',
    measurementId: 'G-HFLE4PSKPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7hIoi4zZcXyy4rJRr7rUI0qtEp9JvDRY',
    appId: '1:1074728173827:android:1c610152f982ea9dbbe936',
    messagingSenderId: '1074728173827',
    projectId: 'studio-l13dd',
    databaseURL: 'https://studio-l13dd-default-rtdb.firebaseio.com',
    storageBucket: 'studio-l13dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdPbKA-n1kpcuL17rG9dmmqpba6y70VYs',
    appId: '1:1074728173827:ios:0b9732fbc65dcbe5bbe936',
    messagingSenderId: '1074728173827',
    projectId: 'studio-l13dd',
    databaseURL: 'https://studio-l13dd-default-rtdb.firebaseio.com',
    storageBucket: 'studio-l13dd.firebasestorage.app',
    androidClientId: '1074728173827-a6867mia33h6aoi02sc57jb4b3635bp3.apps.googleusercontent.com',
    iosClientId: '1074728173827-hfhhefn072itqs1p1hva6udc9b5p4jg6.apps.googleusercontent.com',
    iosBundleId: 'com.surfiniaburger.galacticstreamhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdPbKA-n1kpcuL17rG9dmmqpba6y70VYs',
    appId: '1:1074728173827:ios:0090b31d651f5687bbe936',
    messagingSenderId: '1074728173827',
    projectId: 'studio-l13dd',
    databaseURL: 'https://studio-l13dd-default-rtdb.firebaseio.com',
    storageBucket: 'studio-l13dd.firebasestorage.app',
    androidClientId: '1074728173827-a6867mia33h6aoi02sc57jb4b3635bp3.apps.googleusercontent.com',
    iosClientId: '1074728173827-jv1cgf8dorj178bj0rhj6egqvna90upi.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );

}